/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/pi/catkin_ws/src/rocket/msg/RosGPS.msg
 *
 */


#ifndef ROCKET_MESSAGE_ROSGPS_H
#define ROCKET_MESSAGE_ROSGPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rocket
{
template <class ContainerAllocator>
struct RosGPS_
{
  typedef RosGPS_<ContainerAllocator> Type;

  RosGPS_()
    : gps_time(0.0)
    , ros_time(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , speed(0.0)
    , climb(0.0)
    , eps(0.0)
    , epx(0.0)
    , epy(0.0)
    , epv(0.0)
    , ept(0.0)
    , NSatellites(0)  {
    }
  RosGPS_(const ContainerAllocator& _alloc)
    : gps_time(0.0)
    , ros_time(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , speed(0.0)
    , climb(0.0)
    , eps(0.0)
    , epx(0.0)
    , epy(0.0)
    , epv(0.0)
    , ept(0.0)
    , NSatellites(0)  {
    }



   typedef double _gps_time_type;
  _gps_time_type gps_time;

   typedef double _ros_time_type;
  _ros_time_type ros_time;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _climb_type;
  _climb_type climb;

   typedef double _eps_type;
  _eps_type eps;

   typedef double _epx_type;
  _epx_type epx;

   typedef double _epy_type;
  _epy_type epy;

   typedef double _epv_type;
  _epv_type epv;

   typedef double _ept_type;
  _ept_type ept;

   typedef int32_t _NSatellites_type;
  _NSatellites_type NSatellites;




  typedef boost::shared_ptr< ::rocket::RosGPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocket::RosGPS_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RosGPS_

typedef ::rocket::RosGPS_<std::allocator<void> > RosGPS;

typedef boost::shared_ptr< ::rocket::RosGPS > RosGPSPtr;
typedef boost::shared_ptr< ::rocket::RosGPS const> RosGPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocket::RosGPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocket::RosGPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rocket

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/pi/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'rocket': ['/home/pi/catkin_ws/src/rocket/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rocket::RosGPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocket::RosGPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocket::RosGPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocket::RosGPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocket::RosGPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocket::RosGPS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocket::RosGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03db20eaf6f5d3855a4c7d040a55ed54";
  }

  static const char* value(const ::rocket::RosGPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03db20eaf6f5d385ULL;
  static const uint64_t static_value2 = 0x5a4c7d040a55ed54ULL;
};

template<class ContainerAllocator>
struct DataType< ::rocket::RosGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocket/RosGPS";
  }

  static const char* value(const ::rocket::RosGPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocket::RosGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 gps_time\n\
float64 ros_time\n\
float64 latitude\n\
float64 longitude\n\
float64 altitude\n\
float64 speed\n\
float64 climb \n\
float64 eps \n\
float64 epx \n\
float64 epy \n\
float64 epv\n\
float64 ept\n\
int32 NSatellites\n\
";
  }

  static const char* value(const ::rocket::RosGPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocket::RosGPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gps_time);
      stream.next(m.ros_time);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.speed);
      stream.next(m.climb);
      stream.next(m.eps);
      stream.next(m.epx);
      stream.next(m.epy);
      stream.next(m.epv);
      stream.next(m.ept);
      stream.next(m.NSatellites);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RosGPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocket::RosGPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rocket::RosGPS_<ContainerAllocator>& v)
  {
    s << indent << "gps_time: ";
    Printer<double>::stream(s, indent + "  ", v.gps_time);
    s << indent << "ros_time: ";
    Printer<double>::stream(s, indent + "  ", v.ros_time);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "climb: ";
    Printer<double>::stream(s, indent + "  ", v.climb);
    s << indent << "eps: ";
    Printer<double>::stream(s, indent + "  ", v.eps);
    s << indent << "epx: ";
    Printer<double>::stream(s, indent + "  ", v.epx);
    s << indent << "epy: ";
    Printer<double>::stream(s, indent + "  ", v.epy);
    s << indent << "epv: ";
    Printer<double>::stream(s, indent + "  ", v.epv);
    s << indent << "ept: ";
    Printer<double>::stream(s, indent + "  ", v.ept);
    s << indent << "NSatellites: ";
    Printer<int32_t>::stream(s, indent + "  ", v.NSatellites);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCKET_MESSAGE_ROSGPS_H
